/**
 * This code was autogenerated from a Postman source
 */
const http = require('http');
const PORT = process.env.PORT || 4500;

const server = http.createServer((req, res) => {
  const url = new URL(req.url || '', 'http://localhost');
  const pathname = url.pathname;

  // @endpoint POST /cart
  if (req.method === 'POST' && pathname === '/cart') {
    // Sample response as there are no examples saved on the request.
    res.writeHead(200, { 'Content-Type': 'application/json' });
    return res.end(JSON.stringify({ message: 'Hi from postman mock' }));
  }

  // @endpoint GET /cart
  if (req.method === 'GET' && pathname === '/cart') {
    // Sample response as there are no examples saved on the request.
    res.writeHead(200, { 'Content-Type': 'application/json' });
    return res.end(JSON.stringify({ message: 'Hi from postman mock' }));
  }

  // @endpoint DELETE /cart
  if (req.method === 'DELETE' && pathname === '/cart') {
    // Sample response as there are no examples saved on the request.
    res.writeHead(200, { 'Content-Type': 'application/json' });
    return res.end(JSON.stringify({ message: 'Hi from postman mock' }));
  }

  // @endpoint PUT /cart
  if (req.method === 'PUT' && pathname === '/cart') {
    // Sample response as there are no examples saved on the request.
    res.writeHead(200, { 'Content-Type': 'application/json' });
    return res.end(JSON.stringify({ message: 'Hi from postman mock' }));
  }

  res.writeHead(404, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({ error: 'Endpoint not defined' }));
});

server.listen(PORT);
